using AssetHelperLib.Repacking;
using System.Collections.Generic;
using PPtrInfo = (int fileId, long pathId);

namespace AssetHelperLib.PreloadTable;

/// <summary>
/// Class representing a strategy for building the preload table for a repacked asset.
/// 
/// I don't know what exactly needs to go into the preload table; too few things may cause
/// a crash, too many things may inflate load times.
/// </summary>
public abstract class BasePreloadTableResolver
{
    /// <summary>
    /// Build the preload table for the current asset.
    /// </summary>
    /// <param name="assetPathId">The path id for the asset being repacked.</param>
    /// <param name="ctx">The context containing information about the repacking.</param>
    /// <param name="tableInfos">A hashset of dependencies generated by this resolver.
    /// The fileId should be the one-indexed position in the externals list
    /// for the <see cref="RepackingContext.MainAssetsFileInstance"/>. If the desired
    /// external is not present, it should be added.</param>
    public abstract void BuildPreloadTable(long assetPathId, RepackingContext ctx, ref HashSet<PPtrInfo> tableInfos);
}
